apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration for keycloak

namespace: keycloak

resources:
  - namespace.yaml
  - services.yaml
  - deployment-postgres.yaml
  - statefulset-keycloak.yaml
labels:
  - pairs:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/part-of: ml-platform
    includeSelectors: false

