apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources: []

labels:
  - pairs:
      app.kubernetes.io/name: nfs-provisioner
      app.kubernetes.io/part-of: ml-platform
    includeSelectors: false
